[package]
name = "compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Noctivue compiler frontend (lexer, parser, AST, resolver, typeck, HIR)"

[dependencies]
unicode-ident = "1.0.14"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
lsp-types = "0.97"
url = "2.5"
cranelift-codegen = "0.135.1"
cranelift-frontend = "0.135.1"
cranelift-module = "0.135.1"
cranelift-object = "0.135.1"

[[bin]]
name = "gen_syntax_highlighting"
path = "src/tools/gen_syntax_highlighting.rs"
